# -*- coding: utf-8 -*-
"""Aula1_imersao_dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1oPb5FA4T6_cLm-Adyq1ppXmyt9-lk1

## **Análise de dados**
Base de dados sobre modelos de trabalhos e suas características

### **⬆️Importando e visualizando os dados**
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(5)

df.info()

df.describe()

df.shape

linhas, colunas= df.shape[0], df.shape[1]
print("linhas:", linhas)
print("colunas:", colunas)

df.columns

renomear_colunas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

df.rename(columns=renomear_colunas, inplace=True)

df["senioridade"].value_counts()

df["contrato"].value_counts()

df["remoto"].value_counts()
#0= presencial, 100= remoto, 50= híbrido

df["tamanho_empresa"].value_counts()
#M= médio, L=grande , S= pequena

"""Renomear as categorias das colunas "senioridade", "contrato" e "tamanho_empresa"
"""

senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}
df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

contrato = {
    'FT': 'Tempo integral',
    'PT': 'Parcial',
    'CT': 'Contrato',
    'FL': 'Freelancer'
}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

tamanho_empresa = {
    'L': 'Grande',
    'S': 'Pequena',
    'M': 'Média'

}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

remoto = {
    0: 'Presencial',
    100: 'Remoto',
    50: 'Hibrido'
}

df['remoto'] = df['remoto'].replace(remoto)
df['remoto'].value_counts()

df.head()

df.describe(include="object")

df.describe()

"""###**🧹Limpeza e tratamento dos dados**



"""

df.isnull()

df.isnull().sum()

df["ano"].unique()

df[df.isnull().any(axis=1)]

df_limpo= df.dropna()

df_limpo.isnull().sum()

df_limpo.head()

#converte ano para tipo inteiro
df_limpo= df_limpo.assign(ano=df_limpo['ano'].astype('int64'))

#Salvando o df
df_limpo.to_csv("dados-imersao-final.csv", index=False)
print("Arquivo salvo com sucesso!")

"""###**📊Visualizando os dados**

"""

import seaborn as sns

import matplotlib.pyplot as plt

df_limpo.head()

df_limpo['senioridade'].value_counts().plot(kind= 'bar', title='Distribuição de senioridade')

sns.barplot(data= df_limpo, x='senioridade', y='usd')

#Salário médio por senioridade
color_map = {
    'Junior': '#d6406f',
    'Pleno': '#8b1e3f',
    'Senior': '#b1123b',
    'Executivo': '#5a1027'
}

ordem = df_limpo.groupby("senioridade")["usd"].mean().sort_values(ascending=False).index

plt.figure(figsize=(8,5))
sns.barplot(data= df_limpo, x='senioridade', y='usd', order=ordem, palette=color_map, hue='senioridade', legend=False)
plt.title("Salário médio por senioridade")
plt.xlabel("Senioridade")
plt.ylabel("Salário médio anual(USD)")
plt.show()

#Calcular a média do salário em cada uma das categorias e retornar do menor para o maior valor
df_limpo.groupby("senioridade")["usd"].mean().sort_values(ascending=False)

ordem=df_limpo.groupby("senioridade")["usd"].mean().sort_values(ascending=False).index
ordem

#Média salarial
color_map = {
    'Junior': '#d6406f',
    'Pleno': '#8b1e3f',
    'Senior': '#b1123b',
    'Executivo': '#5a1027'
}
plt.figure(figsize=(8,5))
sns.barplot(data= df_limpo, x='senioridade', y='usd', order=ordem, palette=color_map, hue='senioridade', legend=False)
plt.title("Salário médio por senioridade")
plt.xlabel("Senioridade")
plt.ylabel("Salário médio anual(USD)")
plt.show()

#Distribuição salarial
plt.figure(figsize=(10,5))
sns.histplot(df_limpo['usd'], bins= 50, kde=True, color="#6d2638")
plt.title("Distribuição dos salários anuais")
plt.xlabel("Salário em USD")
plt.ylabel("Frequência")
plt.show()

#Boxplot salário
plt.figure(figsize=(8,5))
sns.boxplot(x=df_limpo['usd'], color="#6d2638")
plt.title("Boxplot Salário")
plt.xlabel("Salário em USD")
plt.show()

#Boxplot de distribuição salarial por nível de senioridade
ordem_senioridade= ["Junior","Pleno","Senior","Executivo"]

color_map = {
    'Junior': '#d6406f',
    'Pleno': '#8b1e3f',
    'Senior': '#b1123b',
    'Executivo': '#5a1027'
}

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade', y='usd', data=df_limpo, order=ordem_senioridade, palette=color_map, hue= 'senioridade')
plt.title("Boxplot de distribuição salarial por nível de senioridade")
plt.xlabel("Salário em USD")
plt.show()

import plotly.express as px

#Média Salarial por Nível de Senioridade
df_senioridade_media = df_limpo.groupby('senioridade')['usd'].mean().reindex(ordem_senioridade)

color_map = {
    'Junior': '#d6406f',
    'Pleno': '#8b1e3f',
    'Senior': '#b1123b',
    'Executivo': '#5a1027'
}

fig = px.bar(
    x=df_senioridade_media.index,
    y=df_senioridade_media.values,
    title='Média Salarial por Nível de Senioridade (USD)',
    labels={'x': 'Nível de Senioridade', 'y': 'Média Salarial (USD)'},
    color=df_senioridade_media.index,
    color_discrete_map=color_map
)

fig.update_layout(xaxis={'categoryorder':'array', 'categoryarray':ordem_senioridade})
fig.show()

#Gráfico de pizza-> Proporção dos tipos de trabalho
remoto_contagem= df_limpo['remoto'].value_counts().reset_index()
remoto_contagem.columns= ['tipo_trabalho', 'quantidade']

color_map_remoto = {
    'Presencial': '#5e616a',
    'Remoto': '#b1123b',
    'Hibrido': '#944459'
}

fig = px.pie(
    remoto_contagem,
    names='tipo_trabalho',
    values='quantidade',
    title='Proporção dos tipos de trabalho',
    hole=0.5,
    color='tipo_trabalho',
    color_discrete_map=color_map_remoto
)

fig.update_traces(textinfo='percent+label')
fig.show()

#Distribuição do Salário Médio de Cientista de Dados por País
df_cientista_dados = df_limpo[df_limpo['cargo'] == 'Data Scientist']
df_salario_pais = df_cientista_dados.groupby('empresa')['usd'].mean().sort_values(ascending=False).reset_index()

# Definindo uma paleta de cores
wine_red_colors = ['#5A1027', '#8B1E3F', '#B1123B', '#D6406F', '#FF6B8B', '#FF9AA2']

fig = px.bar(
    df_salario_pais,
    x='empresa',
    y='usd',
    title='Salário Médio de Cientista de Dados por País (USD)',
    labels={'empresa': 'País da Empresa', 'usd': 'Salário Médio Anual (USD)'},
    color='usd', # Color bars based on salary for a gradient effect
    color_continuous_scale=wine_red_colors[::-1] # Apply the wine-red color scale in reverse
)

fig.update_layout(xaxis_title='País da Empresa', yaxis_title='Salário Médio Anual (USD)')
fig.show()

#Proporção da Média Salarial por Tipo de Contrato
df_contrato_media = df_limpo.groupby('contrato')['usd'].mean().sort_values(ascending=False).reset_index()

color_map_contrato = {
    'Tempo integral': '#36454F',
    'Contrato': '#708090',
    'Parcial': '#A9A9A9',
    'Freelancer': '#D3D3D3'
}

fig = px.pie(
    df_contrato_media,
    names='contrato',
    values='usd',
    title='Proporção da Média Salarial por Tipo de Contrato (USD)',
    color='contrato',
    color_discrete_map=color_map_contrato
)

fig.update_traces(textinfo='percent+label')
fig.show()


import pycountry
#Função para converter ISO-2 para ISO-3 (vai converter a sigla para o código)
def iso2_to_iso3(code):
  try:
    # Garante que o código é uma string e remove quaisquer espaços em branco
    cleaned_code = str(code).strip()
    return pycountry.countries.get(alpha_2=cleaned_code).alpha_3 # Correção: alpha_3 ao invés de alpha3
  except Exception as e:
    print(f"Erro ao converter código '{code}': {e}")
    return None
# Criar nova coluna com código ISO-3
df_limpo['residencia_iso3']= df_limpo['residencia'].apply(iso2_to_iso3)
#Calcular a média salarial por país (ISO-3)
df_ds =df_limpo[df_limpo['cargo'] == 'Data Scientist']

# Filtrar linhas onde 'residencia_iso3' não é nulo antes de agrupar
df_ds_valid_residencia = df_ds.dropna(subset=['residencia_iso3'])

media_ds_pais = df_ds_valid_residencia.groupby('residencia_iso3')['usd'].mean().reset_index()

# Definir a paleta de cores personalizada (vinho, vermelho, rosa)
wine_red_pink_colors = ['#5A1027', '#B1123B', '#D6406F', '#FF6B8B', '#FF9AA2']

#Gerar o mapa
fig= px.choropleth(media_ds_pais,
                   locations='residencia_iso3',
                   color='usd',
                   color_continuous_scale=wine_red_pink_colors, # Usar a paleta personalizada
                   title='Salário médio de Cientista de Dados por país',
                   labels={'usd':'Salário médio(USD)', 'residencia_iso3':'País'})
fig.show()



